# Assignment_4 (2D Arrays)


💡 **Question 1**
Given three integer arrays arr1, arr2 and arr3 **sorted** in **strictly increasing** order, return a sorted array of **only** the integers that appeared in **all** three arrays.

**Example 1:**

Input: arr1 = [1,2,3,4,5], arr2 = [1,2,5,7,9], arr3 = [1,3,4,5,8]

Output: [1,5]

**Explanation:** Only 1 and 5 appeared in the three arrays.


In [12]:
def commonElements(arr1, arr2, arr3):
    
    common_elements = []
    for i in arr1:
        if i in arr2 and i in arr3 and i not in common_elements:
            common_elements.append(i)
    return common_elements


arr1 =  [1,2,3,4,5]
arr2 = [1,2,5,7,9]
arr3 = [1,3,4,5,8]

print(commonElements(arr1,arr2,arr3))  
print(commonElements([1, 1, 2, 2, 3, 3], [2, 2, 3, 3, 4, 4], [3, 3, 4, 4, 5, 5])) 


[1, 5]
[3]



💡 **Question 2**

Given two **0-indexed** integer arrays nums1 and nums2, return *a list* answer *of size* 2 *where:*

- answer[0] *is a list of all **distinct** integers in* nums1 *which are **not** present in* nums2*.*
- answer[1] *is a list of all **distinct** integers in* nums2 *which are **not** present in* nums1.

**Note** that the integers in the lists may be returned in **any** order.

**Example 1:**

**Input:** nums1 = [1,2,3], nums2 = [2,4,6]

**Output:** [[1,3],[4,6]]

**Explanation:**

For nums1, nums1[1] = 2 is present at index 0 of nums2, whereas nums1[0] = 1 and nums1[2] = 3 are not present in nums2. Therefore, answer[0] = [1,3].

For nums2, nums2[0] = 2 is present at index 1 of nums1, whereas nums2[1] = 4 and nums2[2] = 6 are not present in nums2. Therefore, answer[1] = [4,6].




In [53]:
def distinct_array_elements(nums1, nums2):

    answer=[[],[]]
    

    for i in nums1:
        if i not in nums2 and i not in answer[0]:
           answer[0].append(i)
    
    for i in nums2 :
        if i not in nums1 and i not in answer[1]:
           answer[1].append(i)

   
    return answer

nums1 = [1,2,3]
nums2 = [2,4,6]
print(distinct_array_elements(nums1,nums2))
print(distinct_array_elements([1, 2, 2, 2, 3, 3],[2, 2, 3, 3, 4, 4]))
        

[[1, 3], [4, 6]]
[[1], [4]]



💡 **Question 3**
Given a 2D integer array matrix, return *the **transpose** of* matrix.

The **transpose** of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.

**Example 1:**

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]

Output: [[1,4,7],[2,5,8],[3,6,9]]


In [56]:
import numpy as np

def transpose_matrix(matrix):
    
    arr = np.array(matrix)
    transposed = np.transpose(arr)
    return transposed

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(transpose_matrix(matrix))


[[1 4 7]
 [2 5 8]
 [3 6 9]]


💡 **Question 4**
Given an integer array nums of 2n integers, group these integers into n pairs (a1, b1), (a2, b2), ..., (an, bn) such that the sum of min(ai, bi) for all i is **maximized**. Return *the maximized sum*.

**Example 1:**

Input: nums = [1,4,3,2]

Output: 4

**Explanation:** All possible pairings (ignoring the ordering of elements) are:

1. (1, 4), (2, 3) -> min(1, 4) + min(2, 3) = 1 + 2 = 3

2. (1, 3), (2, 4) -> min(1, 3) + min(2, 4) = 1 + 2 = 3

3. (1, 2), (3, 4) -> min(1, 2) + min(3, 4) = 1 + 3 = 4

So the maximum possible sum is 4.


In [57]:
def array_pair_sum(nums):
    nums.sort()  
    max_sum = 0

    for i in range(0, len(nums), 2):
        max_sum += nums[i]

    return max_sum

nums = [1, 4, 3, 2]
max_sum = array_pair_sum(nums)
print(max_sum)  


4



💡 **Question 5**
You have n coins and you want to build a staircase with these coins. The staircase consists of k rows where the ith row has exactly i coins. The last row of the staircase **may be** incomplete.

Given the integer n, return *the number of **complete rows** of the staircase you will build*.

**Example 1:**
    **Input:** n = 5

**Output:** 2

**Explanation:** Because the 3rd row is incomplete, we return 2.


In [66]:
def arrangeCoins(n):
    row = 1
    while n >= row:
        n -= row
        row += 1

    return row - 1

n = 5
result = arrangeCoins(n)
print(result)  # Output: 2


2



💡 **Question 6**
Given an integer array nums sorted in **non-decreasing** order, return *an array of **the squares of each number** sorted in non-decreasing order*.

**Example 1:**

Input: nums = [-4,-1,0,3,10]

Output: [0,1,9,16,100]

**Explanation:** After squaring, the array becomes [16,1,0,9,100].
After sorting, it becomes [0,1,9,16,100]


In [83]:
def square_sorted_arr(nums):
    square_arr =[]
    
    for i in nums:
        square_arr.append(i*i)
    square_arr.sort()
    return square_arr

nums = [-4,-1,0,3,10]
print(square_sorted_arr(nums))

[0, 1, 9, 16, 100]



💡 **Question 7**
You are given an m x n matrix M initialized with all 0's and an array of operations ops, where ops[i] = [ai, bi] means M[x][y] should be incremented by one for all 0 <= x < ai and 0 <= y < bi.

Count and return *the number of maximum integers in the matrix after performing all the operations*

**Example 1:**

![q4.jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/4d0890d0-7bc7-4f59-be8e-352d9f3c1c52/q4.jpg)

**Input:** m = 3, n = 3, ops = [[2,2],[3,3]]

**Output:** 4

**Explanation:** The maximum integer in M is 2, and there are four of it in M. So return 4.



In [86]:
import numpy as np

def maxCount(m, n, ops):
    matrix = np.zeros((m, n), dtype=int)

    for op in ops:
        matrix[:op[0], :op[1]] += 1

    max_value = np.max(matrix)
    count = np.count_nonzero(matrix == max_value)

    return count

m = 3
n = 3
ops = [[2, 2], [3, 3]]
result = maxCount(m, n, ops)
print(result)  # Output: 4


4


💡 **Question 8**

Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

*Return the array in the form* [x1,y1,x2,y2,...,xn,yn].

**Example 1:**

**Input:** nums = [2,5,1,3,4,7], n = 3

**Output:** [2,3,5,4,1,7]

**Explanation:** Since x1=2, x2=5, x3=1, y1=3, y2=4, y3=7 then the answer is [2,3,5,4,1,7].



In [104]:
def array_8(nums):

    new_arr=[]
    n= len(nums)//2

    for i in range(0,n):
    
        new_arr.append(nums[i])
        new_arr.append(nums[n+i])
    
    return new_arr

nums = [2,5,1,3,4,7]
print(array_8(nums))

[2, 3, 5, 4, 1, 7]
