# Assignment-6(2D Arrays)


💡 **Question 1**

A permutation perm of n + 1 integers of all the integers in the range [0, n] can be represented as a string s of length n where:

- s[i] == 'I' if perm[i] < perm[i + 1], and
- s[i] == 'D' if perm[i] > perm[i + 1].

Given a string s, reconstruct the permutation perm and return it. If there are multiple valid permutations perm, return **any of them**.

**Example 1:**

**Input:** s = "IDID"

**Output:**

[0,4,1,3,2]


In [1]:
def reconstruct_permutation(s):
    n = 0
    m = len(s)
    perm = []
    
    for char in s:
        if char == 'I':
            perm.append(n)
            n += 1
        elif char == 'D':
            perm.append(m)
            m -= 1
    
    perm.append(n)  # Append the remaining number
    
    return perm

s = "IDID"
result = reconstruct_permutation(s)
print(result)


[0, 4, 1, 3, 2]



💡 **Question 2**

You are given an m x n integer matrix matrix with the following two properties:

- Each row is sorted in non-decreasing order.
- The first integer of each row is greater than the last integer of the previous row.

Given an integer target, return true *if* target *is in* matrix *or* false *otherwise*.

You must write a solution in O(log(m * n)) time complexity.

**Example 1:**
**Input:** matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3

**Output:** true


In [2]:
def search_matrix(matrix, target):
    m = len(matrix)
    n = len(matrix[0])
    left = 0
    right = m * n - 1
    
    while left <= right:
        mid = (left + right) // 2
        row = mid // n
        col = mid % n
        
        if matrix[row][col] == target:
            return True
        elif matrix[row][col] < target:
            left = mid + 1
        else:
            right = mid - 1
    
    return False

matrix = [[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]]
target = 3
result = search_matrix(matrix, target)
print(result)


True



💡 **Question 3**

Given an array of integers arr, return *true if and only if it is a valid mountain array*.

Recall that arr is a mountain array if and only if:

- arr.length >= 3
- There exists some i with 0 < i < arr.length - 1 such that:
    - arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
    - arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
    
    **Example 1:**

**Input:** arr = [2,1]

**Output:**

false


In [3]:
def valid_mountain_array(arr):
    n = len(arr)
    if n < 3:
        return False
    
    peak = 0
    for i in range(1, n):
        if arr[i] <= arr[i-1]:
            peak = i-1
            break
    if peak == 0 or peak == n-1:
        return False
    
    for i in range(peak+1, n):
        if arr[i] >= arr[i-1]:
            return False
    
    return True

arr = [2, 1]
result = valid_mountain_array(arr)
print(result)



False



💡 **Question 4**

Given a binary array nums, return *the maximum length of a contiguous subarray with an equal number of* 0 *and* 1.

**Example 1:**

**Input:** nums = [0,1]

**Output:** 2

**Explanation:**

[0, 1] is the longest contiguous subarray with an equal number of 0 and 1.



In [4]:
def find_max_length(nums):
    max_length = 0
    count = 0
    prefix_sum = {0: -1}

    for i, num in enumerate(nums):
        count += 1 if num == 1 else -1

        if count in prefix_sum:
            length = i - prefix_sum[count]
            max_length = max(max_length, length)
        else:
            prefix_sum[count] = i

    return max_length

nums = [0, 1]
result = find_max_length(nums)
print(result)


2


💡 **Question 5**

The **product sum** of two equal-length arrays a and b is equal to the sum of a[i] * b[i] for all 0 <= i < a.length (**0-indexed**).

- For example, if a = [1,2,3,4] and b = [5,2,3,1], the **product sum** would be 1*5 + 2*2 + 3*3 + 4*1 = 22.

Given two arrays nums1 and nums2 of length n, return *the **minimum product sum** if you are allowed to **rearrange** the **order** of the elements in* nums1.

**Example 1:**

**Input:** nums1 = [5,3,4,2], nums2 = [4,2,2,5]

**Output:** 40

**Explanation:**

We can rearrange nums1 to become [3,5,4,2]. The product sum of [3,5,4,2] and [4,2,2,5] is 3*4 + 5*2 + 4*2 + 2*5 = 40.



In [6]:
def minimum_product_sum(nums1, nums2):
    nums1.sort()
    nums2.sort(reverse=True)
    min_product_sum = sum(num1 * num2 for num1, num2 in zip(nums1, nums2))
    return min_product_sum

nums1 = [5, 3, 4, 2]
nums2 = [4, 2, 2, 5]
result = minimum_product_sum(nums1, nums2)
print(result)


40



💡 **Question 6**

An integer array original is transformed into a **doubled** array changed by appending **twice the value** of every element in original, and then randomly **shuffling** the resulting array.

Given an array changed, return original *if* changed *is a **doubled** array. If* changed *is not a **doubled** array, return an empty array. The elements in* original *may be returned in **any** order*.

**Example 1:**

**Input:** changed = [1,3,4,2,6,8]

**Output:** [1,3,4]

**Explanation:** One possible original array could be [1,3,4]:

- Twice the value of 1 is 1 * 2 = 2.
- Twice the value of 3 is 3 * 2 = 6.
- Twice the value of 4 is 4 * 2 = 8.

Other original arrays could be [4,3,1] or [3,1,4].



In [47]:

def find_original_array(changed):
    
    half_length=len(changed)//2
    original =[]
    
    for i in range(half_length):
        if 2*changed[i]==changed[half_length+i]: 
            original.append(changed[i])
        else:
            original = []
            break
    
    return original

changed = [1, 3, 4, 2, 6, 8]
original = find_original_array(changed)
print(original)


[1, 3, 4]



💡 **Question 7**

Given a positive integer n, generate an n x n matrix filled with elements from 1 to n2 in spiral order.

**Example 1:**

    **Input:** n = 3

**Output:** [[1,2,3],[8,9,4],[7,6,5]]


In [49]:
import numpy as np

def generate_spiral_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    num = 1
    left, right, top, bottom = 0, n-1, 0, n-1
    
    while num <= n*n:
        # Traverse from left to right
        for i in range(left, right+1):
            matrix[top][i] = num
            num += 1
        top += 1
        
        # Traverse from top to bottom
        for i in range(top, bottom+1):
            matrix[i][right] = num
            num += 1
        right -= 1
        
        # Traverse from right to left
        for i in range(right, left-1, -1):
            matrix[bottom][i] = num
            num += 1
        bottom -= 1
        
        # Traverse from bottom to top
        for i in range(bottom, top-1, -1):
            matrix[i][left] = num
            num += 1
        left += 1
    
    return matrix

# Example usage
n = 3
result = generate_spiral_matrix(n)
print(result)


[[1 2 3]
 [8 9 4]
 [7 6 5]]



💡 **Question 8**

Given two [sparse matrices](https://en.wikipedia.org/wiki/Sparse_matrix) mat1 of size m x k and mat2 of size k x n, return the result of mat1 x mat2. You may assume that multiplication is always possible.

**Example 1:**

**Input:** mat1 = [[1,0,0],[-1,0,3]], mat2 = [[7,0,0],[0,0,0],[0,0,1]]

**Output:**

[[7,0,0],[-7,0,3]]

In [48]:
import numpy as np

mat1 = [[1, 0, 0], [-1, 0, 3]]
mat2 = [[7, 0, 0], [0, 0, 0], [0, 0, 1]]

result = np.dot(mat1, mat2)
print(result)


[[ 7  0  0]
 [-7  0  3]]
